### ISSUE TITLE
Engraving Option to Overwrite (Destroy) Previously Made Metal Plates

### ISSUE THREAD

**Issue by LetsGoHEAT** [seedhammer/seedhammer#1]
Add an option that allows for the destruction of a previously created Steel Plate by sufficiently overwriting the seed words and QR code on the plate so that they become unreadable by humans or camera.  Create this feature so that the overwriting process meets an applicable security threshold.

**Comment by seedhammer** [comment]
The idea is good, but we don't feel confident (at this time) that we can destroy a plate with a high enough assurance that the content is truly unreadable.
