### ISSUE TITLE
Passphrase backup onto any plate via seedsigner, by entering characters manually in device.

### ISSUE THREAD

**Issue by thashm** [seedhammer/seedhammer#10]
An option to backup a random string of characters (which will be mainly used for backing up your passphrase, and characters can be entered manually into the seedsigner) onto your plates. Support up to 100 characters as this is what most hw wallets support.

**Comment by seedhammer** [comment]
We might enable support for backing up setups with passphrase as mentioned in #4 - but to enter the passphrase into the controller software is not only a security issue but also impractical and out of scope.

If you want to back up a passphrase it might be beneficial to use one of the many manual stamping methods/products.

**Comment by thashm** [comment]
If the seed signer is stateless, could you explain how it is a security issue? We enter the seed words into the same device for multi sig backups without passphrases.

In terms of storing the plates with the passphrase, they can be stored in a separate location, away from the seed backups. 

Some people use long passphrases, where they can be forgotten, there exists no solution to back up the passphrase when it may be up to 100 characters, as there is lower case, uppercase, and special characters that the stamps do not exist off the shelf for without having them custom made, which would be very cost prohibitive let alone trying to stamp 100 characters in a neat enough and legible fashion would be cumbersome and open to error.

Existing engraving solutions are out there but that would require entering the passphrase into an unsecure device and also it's very hard to do it, when someone already has the machine to do it with and an easy software controller

**Comment by seedhammer** [comment]
If you are afraid of the SeedHammer or the Raspberry Pi Zero containing listening devices, or being tampered with by previous users. 

Backing up a wallet with passphrase that never is entered into the controller/SeedHammer makes it impossible for the machine to know the wallet. You don’t want to reveal this secret to the machine. 

Passphrase can be secured on many of the conventional steel metal backup solutions out there and stored separately from the SeedHammer plates.

**Comment by mineracks** [comment]
Let's consider the case that you are renting out access to your seedhammer system to third party clients.

The third party is rightly concerned that you may have added some clever concealed electronics that record the seed and xpub information somehow.

So how can they still make use of seedhammer and not risk giving you access to spend their coins?

They could use the multisig setup backed up onto seedhammer plates as a base wallet and then simply add a passphrase that has never touched the seedhammer you have lent them access to.

They could in theory use these base plates to create an infinite number of additional wallets protected by passphrases.

In this way, the seedhammer has done all the heavy complex engraving and then all the user has to do is have a separate and simple system they use to add one more layer of security only they could possibly know or see.

This is why we use the SeedOR system in conjunction with seedhammer to create passphrase backups in metal.

You don't have to use a fancy precision engineered backup tool like SeedOR though- a trip to the hardware store and a few dollars later you have nuts, a bolt and some washers that accomplish more or less the same thing.

**Comment by kawikao** [comment]
I like the idea of being able to use the SH to engrave passphrases. Until then, I would think loading the firmware from scratch in front of the person or giving them instructions would help ease their worry about modified code.
