### ISSUE TITLE
Offset printing x,y coordinates

### ISSUE THREAD

**Issue by satscoffee** [seedhammer/seedhammer#15]
It would be nice to offset the printing if the coordinates are slightly off due to drilling! My plates are about 2.5mm off towards the top... [image](https://github.com/seedhammer/seedhammer/assets/123999813/a1a06e83-07f8-4205-b6f1-33c4b4e4bf56)

It would be very cool to have a calibrate plate function to move the engraving a limited amount and ideally commit to persistent settings on SD card, similar to seedsigner. 

Initial (and easiest, would be) would be to allow for manual x/y changes within a range with warnings saying this could damage the seedhammer and or plate if done incorrectly. 

The better and more reliable enhancement would be to navigate the hammer head to be directly over one of the screws and enter that location. This could help calibrate the initial 0,0 location for engraving and ensure full reproducibility.

If persistence isn't an option, this could be achieved during the setup when we are told to adjust the z axis to ensure proper clearance over the screws. 

Thanks for considering!

**Comment by InfiniteQE** [comment]
> if the coordinates are slightly off due to drilling

Do you mean the coordinates are off because you want to engrave a metal plate that is not a SH0x plate, or because you want to engrave in a slightly different location on the CNC deck ?

**Comment by satscoffee** [comment]
> > if the coordinates are slightly off due to drilling
> 
> 
> 
> Do you mean the coordinates are off because you want to engrave a metal plate that is not a SH0x plate, or because you want to engrave in a slightly different location on the CNC deck ?

The latter, to be used with a SH0x plate. If you look at the image of my plate in the original post, it's not perfectly centered vertically so the calibration would ensure that the engraver knows exactly where the plate is even if there are slight variances due to manufacturing.

**Comment by seedhammer** [comment]
Thank you for the feature request. However: your offset is due to a faulty machine. It should fit much better.

We will continue the conversation about how to handle your RMA case in the established private chat :) 

Closing this one off for now.
