### ISSUE TITLE
Add an Advanced Section to the Software

### ISSUE THREAD

**Issue by satscoffee** [seedhammer/seedhammer#21]
There are two groups of users with radically different needs. Typically these groups are the general population and the UI/process should very easy and straightforward. However, (especially in bitcoin), there are advanced users who want more customization and advanced features. 

Much like other signing devices and wallets/apps, I'm proposing adding a **Danger Zone** or **Advanced** section to the software where you could house many of the features that don't fit the large portion of users. 

It could even be a "secret" or un-shown step to access, (similar to the skip engraving function) by holding down a specific button. You should add warnings and disclosures that the user has to accept, but this would keep the two groups of users happy. 

This option keeps SeedHammer highly relevant to many users so the primary use case of multi signature isn't lost, but flexible use cases are added.

**Comment by seedhammer** [comment]
This is not a bad idea in general, but an issue should have a clear way of being resolved. I suggest you create a new issue with the (first) particular advanced feature you would like to see, and let's discuss it from there. Some general considerations:

- Even if hidden under advanced, a feature should be made fail-safe or at least very hard to misuse in an insecure way.
- Even if hidden under an advanced section, the feature should be designed well and as easy to use as possible.
- Someone needs to implement the feature. Some features may be good ideas, but may not fit into our development priorities.
- Someone needs to maintain the feature. Implementing a feature is one thing, keeping it working is another. Once you have a feature, it's hard to remove again.

The above may be too high a bar for features desired by few advanced users. If there is community interest in implementing and maintaining a feature, we could also consider publishing guides to make custom builds with advanced features included.
