### ISSUE TITLE
Hammer custom title on plates

### ISSUE THREAD

**Issue by mineracks** [seedhammer/seedhammer#3]
It would be handy to have a reserved area of the plate where an arbitrary text entered by the user can be engraved.
Even a small number characters would be useful.

**Comment by seedhammer** [comment]
We'll implement this on our side by using the titles passed to us from the coordinator software.

For Sparrow, that's https://github.com/sparrowwallet/sparrow/issues/911.

For Nunchuk, that's https://github.com/nunchuk-io/nunchuk-android/issues/22

**Comment by Aruk** [comment]
It would be great to be able to set the title independently of the coordinator or offer the possibility to override it in the seedhammer interface. It's a quite useful feature, especially to avoid mix ups when you have multiple sets of plates for different accounts

**Comment by seedhammer** [comment]
> It would be great to be able to set the title independently of the coordinator or offer the possibility to override it in the seedhammer interface. 

We want to keep the UI/UX as simple as possible. And with such a small screen and only 3 buttons it quickly becomes cluttered.

More importantly we wan't to be "the printer", not the configurator (for now at least). Titles of cosigners/keys is not just easier to do in eg. Sparrow (with access to full QWERTY) but also the right place to do so. The descriptor should exactly _describe_ your setup - in essence nothing unknown to the descriptor should be entered in a later process.

> It's a quite useful feature, especially to avoid mix ups when you have multiple sets of plates for different accounts

We can't see how this is not obtained through the descriptors?

**Comment by Aruk** [comment]
> > It would be great to be able to set the title independently of the coordinator or offer the possibility to override it in the seedhammer interface.
> 
> We want to keep the UI/UX as simple as possible. And with such a small screen and only 3 buttons it quickly becomes cluttered.
> 
> More importantly we wan't to be "the printer", not the configurator (for now at least). Titles of cosigners/keys is not just easier to do in eg. Sparrow (with access to full QWERTY) but also the right place to do so. The descriptor should exactly _describe_ your setup - in essence nothing unknown to the descriptor should be entered in a later process.

Alright, makes sense!
 
> > It's a quite useful feature, especially to avoid mix ups when you have multiple sets of plates for different accounts
> 
> We can't see how this is not obtained through the descriptors?

Basically you have 3 account which are each a 2 of 3, you end up with 9 plates and want to restore your 3 wallets, which pairs (of descriptor parts) do you scan ?

**Comment by seedhammer** [comment]
> Basically you have 3 account which are each a 2 of 3, you end up with 9 plates and want to restore your 3 wallets, which pairs (of descriptor parts) do you scan ?

Assuming we have implemented this feature:

Those that identifies themself as being part of the same setup. 

Eg scan these two:

1/3 “Satoshi’s stash”
3/3 “ Satoshi’s stash”

and these two:

1/3 “Alice’s stash”
2/3 “Alice’s stash”

…

However it isn’t a real world problem. If you ever want to collect the quorum of a setup (in order to restore) you probably never would gather more than one multisig wallet at a time (would be a honeypot of dimensions). 
And if you take the risk anyways then just scan all plates from a to z until a wallet reveals. As soon as the first workable wallet is identified you can see the mfp’s in the coordinator software and remove those plates from the pot of plates at hand (mfp always hammered on each plate).

**Comment by satscoffee** [comment]
> > It would be great to be able to set the title independently of the coordinator or offer the possibility to override it in the seedhammer interface. 
> 
> 
> 
> We want to keep the UI/UX as simple as possible. And with such a small screen and only 3 buttons it quickly becomes cluttered.
> 
> 
> 
> More importantly we wan't to be "the printer", not the configurator (for now at least). Titles of cosigners/keys is not just easier to do in eg. Sparrow (with access to full QWERTY) but also the right place to do so. The descriptor should exactly _describe_ your setup - in essence nothing unknown to the descriptor should be entered in a later process.
> 
> 
> 
> > It's a quite useful feature, especially to avoid mix ups when you have multiple sets of plates for different accounts
> 
> 
> 
> We can't see how this is not obtained through the descriptors?

I feel like this could be accomplished by having two label options: one during setup and a second after engraving. This should be very limited in terms of locations/orientations and size/characters. 

The first option could be to add text during setup. After completing the seed and verifying, you could ask "Do you want to add a label?" With "[Yes]/[No]/[Back]" as buttons. If yes, then show the plate to be used with location(s) highlighted and move/select location with the d-pad. The locations would be limited based on plate configuration. 

With single sig, locations are possibly above and below the QR and then above and below the 13-24 words or possibly the entire back for a 12 word seed, if someone wanted to be wordy. With 2/3 multisig, it would probably only be to the right of the seed words and turned -90°/vertical. 

Once the location(s) are selected, user enters text for each location with the keyboard like seed phrase and confirms when complete. Confirm final setup and continue engraving. 

The second option could be selected during the initial setup screen (Backup Single, Backup Multisig, Engrave a Label). The first question after selecting Engrave, is "Which plate?" showing the plate name and a basic schematic with location(s) highlighted using left right to toggle between plates, similar to the initial selection screen. Second question is "Which location?" then follow the same UI/UX to select the template area, and enter text as above.

One area of potential trouble could be if a user enters their BIP39 phrase, then that plate is a honeypot. Overcome this with warnings discussing best practices of keeping these separate and a click "Accept" or "I understand". Can't think of many more issues outside of the coding, which I don't do ;)

**Comment by seedhammer** [comment]
Backup titles have been implemented in [v1.2.0](https://github.com/seedhammer/seedhammer/releases/tag/v1.2.0) for supported wallets.

> We'll implement this on our side by using the titles passed to us from the coordinator software.
> 
> For Sparrow, that's [sparrowwallet/sparrow#911](https://github.com/sparrowwallet/sparrow/issues/911).
> 

This was just keystore (co-signer) labels and is not used for titles. We brought up the issue of adding wallet titles to the [Sparrow/Blockchain Commons format](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-010-output-desc.md#deprecated-superseded-by-version-3-output-descriptors), but since the format is not deprecated, titles are unlikely to be implemented for Sparrow exports. Use the BlueWallet export option as a workaround.
