### ISSUE TITLE
[Feature request] User option between SeedQR and CompaxtSeedQR formats

### ISSUE THREAD

**Issue by InfiniteQE** [seedhammer/seedhammer#5]
Currently Seedhammer only supports CompactSeedQR format for the QR code of a BIP39 mnemonic seed.

Whilst this binary encoding is well documented in the seedsigner documentation, and is very rational, "If you're manually punching holes into a metal SeedQR plate, that's cutting out about 35-40% of the work!", with a CNC engraving machine the number of squares is less of an issue.

Given the tradeoffs : 
- recoverability / decoding
- the data cannot be transcribed back to the mnemonic seed easily by hand
- not a BIP, how do we know there won't be a future incompatible BIP or Blockchain Commons standard in the future that replaces CompactSeedQR

Please consider adding a UX option to choose between CompactSeedQR and SeedQR codes.

**Comment by seedhammer** [comment]
Adding UI options has a high bar to keep the controller simple. To address your points:

> recoverability / decoding

Is this an issue? The QR codes are engraved in "high" error correction, not "low" as suggested by the CompactSeedQR spec.

Regardless, the seed phrase is engraved as words for this very reason.

> the data cannot be transcribed back to the mnemonic seed easily by hand

What do you mean? Why is transcribing a SeedQR easier? If you mean by scanning the SeedQR with a insecure software, I consider that a feature.

> not a BIP, how do we know there won't be a future incompatible BIP or Blockchain Commons standard in the future that replaces CompactSeedQR

Is SeedQR a BIP?

**Comment by seedhammer** [comment]
If no further comments we will close this issue?
