### ISSUE TITLE
[Feature Request] 24 word mnemonic engraving option, all on a single side of SH01

### ISSUE THREAD

**Issue by InfiniteQE** [seedhammer/seedhammer#6]
I believe support for 24 word mnemonic was a late feature addition to v0.9.0 

Currently a 24 word mnemonic requires 2 sides of a SH01 plate, this is due the the need for 24 words plus a CompactSeedQR, and makes sense due to the close synergy with Seedsigner.

However I want to use Seedhammer not just with stateless hardware wallets but also with devices like Coldcard, Passport and Bitbox02.  As these hardware wallets use 1-2 secure elements I am comfortable including them as part of my multi-vendor multisig in a non-stateless manner. 

If it were possible to squeeze a 24 words mnemonic on a single side of a SH01 plate (whether with just a smaller font, or with engraving the first 4 letters, or leaving out the CompactSeedQR) that would allow users to hide their mnemonic by using a singe blank plate (15 pairs in the 30 pack), whereas since both sides of SH01 are engraved, one would need 2 blank plates to cover the single engraved plate (10 triplets in the 30 pack).

Thanks

**Comment by satscoffee** [comment]
+1 
I feel this would be a great solution for 24 word. I like the 4 letter option as the font needs to be a decent size and keeping the QR is my preference...

**Comment by cody-wastaken** [comment]
+1 with a twist - the front of the plate would be two 12-word columns and the back of the plate would be a CompactSeedQR (21x21) or possible option to select a SeedQR as requested in issue #5.

This also gives users the option to engrave each side to it's own plate which would permit concealing the contents if you screwed each half together.

**Comment by InfiniteQE** [comment]
@cody-wastaken that is a great idea, as you say it would allow engraving on 2 separate plates to join them face to face, but also the user could choose to dry-run the QR code engraving entirely. The QR is very useful for stateless Seedsigner / Jade but not useful for Coldcard / etc which don't have a camera

**Comment by seedhammer** [comment]
I believe we already support your use case.

1) Create or import your singlesig wallet in eg. Sparrow.
2) Ask Sparrow to show the descriptor (little QR-icon under "Script Policy")
3) Scan the descriptor QR with the SeedHammer software ("Backup Multisig").

You will now be able to hammer either 12 or 24 words on SH01 or SH02 respectively.

As this work flow seems counterintuitive we consider redesigning the front-page of the app.
