### ISSUE TITLE
[Feature Request] Support for testnet3 and tpub addresses

### ISSUE THREAD

**Issue by cody-wastaken** [seedhammer/seedhammer#7]
In order to support testing with actual transactions, support for testnet3 would be extremely valuable. Especially when we are in a high fee environment such as the one we are currently experiencing. This would facilitate testing various setups, doing live demos, and trying other wallet configurations (e.g. blinded xpubs).

**Comment by seedhammer** [comment]
Good idea. This will be supported in the next release.
