### ISSUE TITLE
[Feature Request] Support to print the Output Descriptors QRs in paper

### ISSUE THREAD

**Issue by maxirosson** [seedhammer/seedhammer#8]
It would be very useful for users that can't buy a SeedHammer or just want to try the concept before buying. 

The idea is to generate the Output Descriptors QRs with the software and then have support to send those to a printer, so the user can print the QRs on paper. We should be able to do that without using any other computer, I mean, connecting directly to the printer, probably by USB, Bluetooth, or SdCard. For security reasons, the printer will only receive the QRs containing the BSMS info, NOT the private keys.

**Comment by seedhammer** [comment]
> It would be very useful for users that can't buy a SeedHammer or just want to try the concept before buying.

We agree. To be able to "print" the plates (instead of hammering them) would be a really nice demo-feature.
 
> The idea is to generate the Output Descriptors QRs with the software and then have support to send those to a printer, so the user can print the QRs on paper. We should be able to do that without using any other computer, I mean, connecting directly to the printer, probably by USB, Bluetooth, or SdCard. 

Is this really necessary as the descriptor can be printed from the coordinator software already?

**Comment by maxirosson** [comment]
Yes, you are right. For example, Nunchuk could add support to directly generate the 3 QRs and download them.

**Comment by maxirosson** [comment]
I created this issue on nunchuk https://github.com/nunchuk-io/nunchuk-android/issues/21

**Comment by seedhammer** [comment]
Closed.
